export const studentData = [
  {
    name: "Adewale Stephen",
    email: "adewalestephennifemi@gmail.com",
    reg: "REG001",
    record: "95%",
    course: "Cyber Security",
  },
  {
    name: "Alice Smith",
    email: "alice.smith@example.com",
    reg: "REG002",
    record: "88%",
    course: "Mathematics",
  },
  {
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    reg: "REG003",
    record: "92%",
    course: "Physics",
  },
  {
    name: "Catherine Brown",
    email: "catherine.brown@example.com",
    reg: "REG004",
    record: "85%",
    course: "Chemistry",
  },
  {
    name: "David Wilson",
    email: "david.wilson@example.com",
    reg: "REG005",
    record: "78%",
    course: "Biology",
  },
  {
    name: "Eva Taylor",
    email: "eva.taylor@example.com",
    reg: "REG006",
    record: "90%",
    course: "Engineering",
  },
  {
    name: "Frank Martin",
    email: "frank.martin@example.com",
    reg: "REG007",
    record: "82%",
    course: "Information Technology",
  },
  {
    name: "Grace Lee",
    email: "grace.lee@example.com",
    reg: "REG008",
    record: "91%",
    course: "Data Science",
  },
  {
    name: "Henry Hall",
    email: "henry.hall@example.com",
    reg: "REG009",
    record: "87%",
    course: "Business Administration",
  },
  {
    name: "Isabella Young",
    email: "isabella.young@example.com",
    reg: "REG010",
    record: "93%",
    course: "Graphic Design",
  },
  {
    name: "Jack King",
    email: "jack.king@example.com",
    reg: "REG011",
    record: "89%",
    course: "Economics",
  },
  {
    name: "Lily Scott",
    email: "lily.scott@example.com",
    reg: "REG012",
    record: "95%",
    course: "Philosophy",
  },
  {
    name: "Michael Green",
    email: "michael.green@example.com",
    reg: "REG013",
    record: "76%",
    course: "History",
  },
  {
    name: "Natalie Adams",
    email: "natalie.adams@example.com",
    reg: "REG014",
    record: "88%",
    course: "Political Science",
  },
  {
    name: "Oliver Baker",
    email: "oliver.baker@example.com",
    reg: "REG015",
    record: "90%",
    course: "Environmental Science",
  },
  {
    name: "Penelope Carter",
    email: "penelope.carter@example.com",
    reg: "REG016",
    record: "84%",
    course: "Sociology",
  },
  {
    name: "Quentin Murphy",
    email: "quentin.murphy@example.com",
    reg: "REG017",
    record: "91%",
    course: "Journalism",
  },
  {
    name: "Rachel Foster",
    email: "rachel.foster@example.com",
    reg: "REG018",
    record: "87%",
    course: "Linguistics",
  },
  {
    name: "Samuel Reed",
    email: "samuel.reed@example.com",
    reg: "REG019",
    record: "82%",
    course: "Astronomy",
  },
  {
    name: "Tina Nelson",
    email: "tina.nelson@example.com",
    reg: "REG020",
    record: "79%",
    course: "Acting",
  },
  {
    name: "Ulysses Parker",
    email: "ulysses.parker@example.com",
    reg: "REG021",
    record: "86%",
    course: "Music",
  },
  {
    name: "Violet Turner",
    email: "violet.turner@example.com",
    reg: "REG022",
    record: "92%",
    course: "Fashion Design",
  },
  {
    name: "William Collins",
    email: "william.collins@example.com",
    reg: "REG023",
    record: "80%",
    course: "Theater",
  },
  {
    name: "Xena Rivera",
    email: "xena.rivera@example.com",
    reg: "REG024",
    record: "94%",
    course: "Interior Design",
  },
  {
    name: "Yvonne Cooper",
    email: "yvonne.cooper@example.com",
    reg: "REG025",
    record: "88%",
    course: "Fine Arts",
  },
  {
    name: "Zachary Murphy",
    email: "zachary.murphy@example.com",
    reg: "REG026",
    record: "83%",
    course: "Web Development",
  },
  {
    name: "Amelia Reyes",
    email: "amelia.reyes@example.com",
    reg: "REG027",
    record: "91%",
    course: "Cybersecurity",
  },
  {
    name: "Benjamin Hughes",
    email: "benjamin.hughes@example.com",
    reg: "REG028",
    record: "75%",
    course: "Network Administration",
  },
  {
    name: "Clara Price",
    email: "clara.price@example.com",
    reg: "REG029",
    record: "89%",
    course: "Game Design",
  },
  {
    name: "Derek Ward",
    email: "derek.ward@example.com",
    reg: "REG030",
    record: "97%",
    course: "Artificial Intelligence",
  },
  {
    name: "Ella Torres",
    email: "ella.torres@example.com",
    reg: "REG031",
    record: "85%",
    course: "Statistics",
  },
  {
    name: "Felix Hughes",
    email: "felix.hughes@example.com",
    reg: "REG032",
    record: "90%",
    course: "Pharmacy",
  },
  {
    name: "Gina Price",
    email: "gina.price@example.com",
    reg: "REG033",
    record: "78%",
    course: "Physical Therapy",
  },
  {
    name: "Henry Knight",
    email: "henry.knight@example.com",
    reg: "REG034",
    record: "84%",
    course: "Civil Engineering",
  },
  {
    name: "Ivy Sanders",
    email: "ivy.sanders@example.com",
    reg: "REG035",
    record: "92%",
    course: "Marketing",
  },
  {
    name: "Jake Powell",
    email: "jake.powell@example.com",
    reg: "REG036",
    record: "77%",
    course: "Hospitality Management",
  },
  {
    name: "Kara Baker",
    email: "kara.baker@example.com",
    reg: "REG037",
    record: "88%",
    course: "Sports Science",
  },
  {
    name: "Leo Murphy",
    email: "leo.murphy@example.com",
    reg: "REG038",
    record: "93%",
    course: "Nutrition",
  },
  {
    name: "Mia Ramirez",
    email: "mia.ramirez@example.com",
    reg: "REG039",
    record: "81%",
    course: "Creative Writing",
  },
  {
    name: "Noah Johnson",
    email: "noah.johnson@example.com",
    reg: "REG040",
    record: "86%",
    course: "Theology",
  },
  {
    name: "Olivia White",
    email: "olivia.white@example.com",
    reg: "REG041",
    record: "89%",
    course: "Film Studies",
  },
  {
    name: "Paul Thomas",
    email: "paul.thomas@example.com",
    reg: "REG042",
    record: "82%",
    course: "Fashion Marketing",
  },
  {
    name: "Quinn Harris",
    email: "quinn.harris@example.com",
    reg: "REG043",
    record: "80%",
    course: "Photography",
  },
  {
    name: "Rita Bailey",
    email: "rita.bailey@example.com",
    reg: "REG044",
    record: "94%",
    course: "Urban Planning",
  },
  {
    name: "Steve Young",
    email: "steve.young@example.com",
    reg: "REG045",
    record: "75%",
    course: "Veterinary Science",
  },
  {
    name: "Tara Simmons",
    email: "tara.simmons@example.com",
    reg: "REG046",
    record: "90%",
    course: "Music Production",
  },
  {
    name: "Ursula Jenkins",
    email: "ursula.jenkins@example.com",
    reg: "REG047",
    record: "86%",
    course: "Astrophysics",
  },
  {
    name: "Victor Flores",
    email: "victor.flores@example.com",
    reg: "REG048",
    record: "91%",
    course: "Information Systems",
  },
  {
    name: "Wendy Knight",
    email: "wendy.knight@example.com",
    reg: "REG049",
    record: "87%",
    course: "Geology",
  },
  {
    name: "Xander Cooper",
    email: "xander.cooper@example.com",
    reg: "REG050",
    record: "78%",
    course: "Public Relations",
  },
  {
    name: "Yara Long",
    email: "yara.long@example.com",
    reg: "REG051",
    record: "92%",
    course: "Animation",
  },
  {
    name: "Zane Brooks",
    email: "zane.brooks@example.com",
    reg: "REG052",
    record: "84%",
    course: "Web Design",
  },
  {
    name: "Ada Morgan",
    email: "ada.morgan@example.com",
    reg: "REG053",
    record: "88%",
    course: "History of Art",
  },
  {
    name: "Bradley Turner",
    email: "bradley.turner@example.com",
    reg: "REG054",
    record: "81%",
    course: "Culinary Arts",
  },
  {
    name: "Chloe Wright",
    email: "chloe.wright@example.com",
    reg: "REG055",
    record: "90%",
    course: "Public Health",
  },
  {
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    reg: "REG056",
    record: "93%",
    course: "Meteorology",
  },
  {
    name: "Emily Kim",
    email: "emily.kim@example.com",
    reg: "REG057",
    record: "75%",
    course: "Artificial Intelligence",
  },
  {
    name: "Frankie Stone",
    email: "frankie.stone@example.com",
    reg: "REG058",
    record: "89%",
    course: "Wildlife Conservation",
  },
  {
    name: "Gloria Simmons",
    email: "gloria.simmons@example.com",
    reg: "REG059",
    record: "82%",
    course: "Graphic Communication",
  },
  {
    name: "Henry Bell",
    email: "henry.bell@example.com",
    reg: "REG060",
    record: "96%",
    course: "Cyberpsychology",
  },
  {
    name: "Iris Stevens",
    email: "iris.stevens@example.com",
    reg: "REG061",
    record: "88%",
    course: "Media Studies",
  },
  {
    name: "James Turner",
    email: "james.turner@example.com",
    reg: "REG062",
    record: "81%",
    course: "Dance",
  },
  {
    name: "Kylie Thompson",
    email: "kylie.thompson@example.com",
    reg: "REG063",
    record: "92%",
    course: "App Development",
  },
  {
    name: "Liam Foster",
    email: "liam.foster@example.com",
    reg: "REG064",
    record: "76%",
    course: "Philosophy",
  },
  {
    name: "Monica Rivera",
    email: "monica.rivera@example.com",
    reg: "REG065",
    record: "90%",
    course: "Criminal Justice",
  },
  {
    name: "Nate Garcia",
    email: "nate.garcia@example.com",
    reg: "REG066",
    record: "82%",
    course: "Information Management",
  },
  {
    name: "Olive Hayes",
    email: "olive.hayes@example.com",
    reg: "REG067",
    record: "89%",
    course: "Graphic Arts",
  },
  {
    name: "Penny Brooks",
    email: "penny.brooks@example.com",
    reg: "REG068",
    record: "87%",
    course: "Event Management",
  },
  {
    name: "Quincy Adams",
    email: "quincy.adams@example.com",
    reg: "REG069",
    record: "84%",
    course: "Software Engineering",
  },
  {
    name: "Riley Watson",
    email: "riley.watson@example.com",
    reg: "REG070",
    record: "80%",
    course: "Artificial Intelligence",
  },
  {
    name: "Sophia Ramirez",
    email: "sophia.ramirez@example.com",
    reg: "REG071",
    record: "91%",
    course: "Robotics",
  },
  {
    name: "Trevor Jenkins",
    email: "trevor.jenkins@example.com",
    reg: "REG072",
    record: "78%",
    course: "Clinical Psychology",
  },
  {
    name: "Uma Patel",
    email: "uma.patel@example.com",
    reg: "REG073",
    record: "96%",
    course: "Pharmaceutical Sciences",
  },
  {
    name: "Victor James",
    email: "victor.james@example.com",
    reg: "REG074",
    record: "86%",
    course: "Game Development",
  },
  {
    name: "Willa Cross",
    email: "willa.cross@example.com",
    reg: "REG075",
    record: "75%",
    course: "Social Work",
  },
  {
    name: "Xena Brooks",
    email: "xena.brooks@example.com",
    reg: "REG076",
    record: "89%",
    course: "Human Resource Management",
  },
  {
    name: "Yasmin Hill",
    email: "yasmin.hill@example.com",
    reg: "REG077",
    record: "90%",
    course: "Biotechnology",
  },
  {
    name: "Zara Young",
    email: "zara.young@example.com",
    reg: "REG078",
    record: "92%",
    course: "Ethics",
  },
  {
    name: "Aaron Wood",
    email: "aaron.wood@example.com",
    reg: "REG079",
    record: "80%",
    course: "Mechanical Engineering",
  },
  {
    name: "Brianna Clark",
    email: "brianna.clark@example.com",
    reg: "REG080",
    record: "84%",
    course: "Interior Architecture",
  },
  {
    name: "Cody Wright",
    email: "cody.wright@example.com",
    reg: "REG081",
    record: "87%",
    course: "Nursing",
  },
  {
    name: "Daphne Rivera",
    email: "daphne.rivera@example.com",
    reg: "REG082",
    record: "91%",
    course: "Public Policy",
  },
  {
    name: "Ethan Collins",
    email: "ethan.collins@example.com",
    reg: "REG083",
    record: "79%",
    course: "Digital Marketing",
  },
  {
    name: "Fiona Miller",
    email: "fiona.miller@example.com",
    reg: "REG084",
    record: "93%",
    course: "Social Media Management",
  },
  {
    name: "George Lewis",
    email: "george.lewis@example.com",
    reg: "REG085",
    record: "82%",
    course: "Cyber Law",
  },
  {
    name: "Haley Nguyen",
    email: "haley.nguyen@example.com",
    reg: "REG086",
    record: "88%",
    course: "Occupational Therapy",
  },
  {
    name: "Ian Patterson",
    email: "ian.patterson@example.com",
    reg: "REG087",
    record: "94%",
    course: "Apparel Design",
  },
  {
    name: "Jasmine Turner",
    email: "jasmine.turner@example.com",
    reg: "REG088",
    record: "80%",
    course: "Statistics",
  },
  {
    name: "Kevin Reed",
    email: "kevin.reed@example.com",
    reg: "REG089",
    record: "85%",
    course: "Game Theory",
  },
  {
    name: "Laura Sanders",
    email: "laura.sanders@example.com",
    reg: "REG090",
    record: "90%",
    course: "Sustainability",
  },
  {
    name: "Marcus Foster",
    email: "marcus.foster@example.com",
    reg: "REG091",
    record: "76%",
    course: "Music Therapy",
  },
  {
    name: "Nina Gonzalez",
    email: "nina.gonzalez@example.com",
    reg: "REG092",
    record: "92%",
    course: "Fashion Design",
  },
  {
    name: "Oscar Bennett",
    email: "oscar.bennett@example.com",
    reg: "REG093",
    record: "91%",
    course: "Computer Animation",
  },
  {
    name: "Paula Hayes",
    email: "paula.hayes@example.com",
    reg: "REG094",
    record: "88%",
    course: "Health Sciences",
  },
  {
    name: "Quincy Bell",
    email: "quincy.bell@example.com",
    reg: "REG095",
    record: "80%",
    course: "Wine Studies",
  },
  {
    name: "Ronald Price",
    email: "ronald.price@example.com",
    reg: "REG096",
    record: "89%",
    course: "Aviation",
  },
  {
    name: "Samantha King",
    email: "samantha.king@example.com",
    reg: "REG097",
    record: "93%",
    course: "Applied Science",
  },
  {
    name: "Trevor Price",
    email: "trevor.price@example.com",
    reg: "REG098",
    record: "90%",
    course: "Fire Science",
  },
  {
    name: "Ursula Mitchell",
    email: "ursula.mitchell@example.com",
    reg: "REG099",
    record: "85%",
    course: "Marine Biology",
  },
  {
    name: "Vera Ward",
    email: "vera.ward@example.com",
    reg: "REG100",
    record: "87%",
    course: "Ethnomusicology",
  },
];
